[build]
  publish = "Ghostvault_Website"

[[redirects]]
  from = "/members/*"
  to = "/login.html"
  status = 401
  force = true
  conditions = { Role = ["member"] }

[[redirects]]
  from = "/downloads/*"
  to = "/login.html"
  status = 401
  force = true
  conditions = { Role = ["member"] }


